---

spring:
  profiles: bbmri

broker:
  bona-fide-status-attr: bona_fide_status
  bona-fide-status-rems-attr: bona_fide_status_rems
  group-affiliations-attr: groupAffiliations
  terms-and-policies-group-id: 1
  affiliations-attr: affiliations
  org-url-attr: orgUrl
  ext-source-name: ext-source-name
  issuer: issuer
  path-to-jwk-file: path
adapter:
  adapter-primary: rpc
  call-fallback: false
ldap:
  host: host
  user: user
  password: password
  base-dn: dn
  use-tls: false
  use-ssl: true
  allow-untrusted-ssl: false
  timeout-secs: 10
  port: 636
rpc:
  enabled: true
  url: url
  username: username
  password: password
  serializer: json
attributes:
  attributeMappings:
    bona_fide_status:
      internal-name: bona_fide_status
      rpc-name: urn:perun:user:attribute-def:def:bonaFideStatus
      ldap-name: bonaFideStatus
    bona_fide_status_rems:
      internal-name: bona_fide_status_rems
      rpc-name: urn:perun:user:attribute-def:def:elixirBonaFideStatusREMS
      ldap-name: bonaFideStatusREMS
    groupAffiliations:
      internal-name: groupAffiliations
      rpc-name: urn:perun:group:attribute-def:def:groupAffiliations
      ldap-name: groupAffiliations
    affiliations:
      internal-name: affiliations
      rpc-name: urn:perun:ues:attribute-def:def:affiliation
      ldap-name:
    orgUrl:
      internal-name: orgUrl
      rpc-name: urn:perun:ues:attribute-def:def:organizationURL
      ldap-name:
ga4gh:
  repos:
        -
          name: repo1
          url: url1
          jwks: jwks1
          headers:
            -
              header: header
              value: value
        -
          name: repo2
          url: url2
          jwks: jwks2
          headers:
            -
              header: header
              value: value
basic-auth:
  username: Honza
  password: Lojza
